[JH] 모달 컴포넌트 구현
boostcamp-2020/Project09-A-Uber pull request #87
Opened 2020-11-29 13:09 UTC by hoo00nn

### 작업 사항
- [x] 오더 상세 표시 구현할 때 사용하기 위해 모달 컴포넌트 구현(다른 곳에도 재사용가능하도록)
- [x] useModal 커스텀훅 구현
- [x] modal 렌더링 최적화 (modal로 인해 다른 컴포넌트가 리렌더링 되지않도록) 

### 요약
- 재사용 가능하도록 modal 컴포넌트 구현해보았습니다.
- useModal과 함께 사용하시면 되고, useModal은 리턴 값으로 [isModal, openModal, closeModal] 을 리턴하는 IsModal은 모달의 오픈여부로 Modal 컴포넌트의 visible props에 전달해주시면 되고, openModal은 모달을 열고싶은 버튼에 onClick으로 넣어주시면 되고, closeModal은 Modal 컴포넌트에 onClose props에 전달해주시면 동작됩니다!

### 첨부
![Nov-29-2020 22-04-08](https://user-images.githubusercontent.com/52775389/100542683-eeea2800-328e-11eb-8354-d7a85494462f.gif)

### 이슈
#86

2020-11-29 13:26 UTC, cyjo9603 requested changes

2020-11-29 13:26 UTC, cyjo9603 commented on client/src/components/Modal/Modal.tsx
> +  visible?: boolean;
FB2: `boolean`이 선택적 인자인 경우 기본값으로 `false`(기능에 따라 `true`도 가능)을 주는것이 좋습니다.

2020-11-29 13:26 UTC, cyjo9603 commented on client/src/components/Modal/Modal.tsx
> +      <ModalOverlay visible={visible}></ModalOverlay>
FB2: 이부분은 하나로 children이 없어서 하나로 합치는게 좋아 보이네용

2020-11-29 13:26 UTC, cyjo9603 commented on client/src/components/Modal/Modal.tsx
> +`;
FB2: 파일 하나에 스타일이 너무 분리되어 있다는 생각이 드네용...

2020-11-29 13:26 UTC, cyjo9603 commented on client/src/utils/portal.tsx
> +};
GOOD: 모달 구현할 때 Portal 사용한거 너무 좋습니다 👍👍👍

2020-11-29 13:26 UTC, cyjo9603 commented on client/src/hooks/useModal.ts
> +};
GOOD: 앞으로 모달 사용할 일이 많을 것 같았는데 커스텀 훅 구현하신거 너무 좋은것 같아요 👍👍

2020-11-29 13:28 UTC, hoo00nn commented on client/src/components/Modal/Modal.tsx
> +      <ModalOverlay visible={visible}></ModalOverlay>
수정했습니다!

2020-11-29 13:29 UTC, hoo00nn commented on client/src/components/Modal/Modal.tsx
> +`;
따로 스타일 파일을 두면 좋겠다는 의견이신가요??

2020-11-29 13:33 UTC, cyjo9603 commented on client/src/components/Modal/Modal.tsx
> +`;
흠... 아니요 사실 따로 스타일 파일을 둘 정도이면 컴포넌트를 분리하는게 맞다고 생각하는데 이정도면 styled 컴포넌트 하나에 스타일을 묶어놓는게 좀 더 좋아보여서용

2020-11-29 13:33 UTC, hoo00nn commented on client/src/components/Modal/Modal.tsx
> +  visible?: boolean;
추가했습니다 ㅎㅎ 피드백 고맙습니다 🙆🏻‍♂️

2020-11-29 13:39 UTC, hoo00nn commented on client/src/components/Modal/Modal.tsx
> +`;
음.. 보통 스타일 컴포넌트가 많아질 경우 분리하는게 맞다고 생각하는데 Modal의 경우 역할이 너무 명확해서 Overlay Wrapper Inner를 합친 것을 하나의 컴포넌트로 보는게 맞다고 생각해서 작업했습니다! 
그래서 작업하다 보니 스타일이 길어져 가독성이 떨어져서 분리해두었습니다!

2020-11-29 13:41 UTC, hoo00nn commented on client/src/components/Modal/Modal.tsx
> +`;
재사용이 되는 단위를 컴포넌트로 봤을 때 Modal 자체가 컴포넌트가 되는 것이 맞다고 생각이 들었어요!

2020-11-29 13:47 UTC, cyjo9603 commented on client/src/components/Modal/Modal.tsx
> +`;
음... 듣고나니 그런것 같긴 하네요 ㅋㅋㅋㅋㅋ 죠습니다 👍👍👍

2020-11-29 13:48 UTC, cyjo9603 approved these changes
주말에도 열일.... 고생하셨습니당 👍👍

2020-11-29 13:49 UTC, Kimakjun commented on client/src/hooks/useModal.ts
> +};
GOOD: 커스텀훅 좋습니다!!~!

2020-11-30 00:50 UTC, jongeunk0613 approved these changes

2020-11-30 00:50 UTC, jongeunk0613 commented on client/src/utils/portal.tsx
> +};
GOOD: 리렌더링 되지 않도록 컴포넌트를 분리하는 방법에는 이런 방법도 있군요!! 배워갑니다 👍

2020-11-30 01:04 UTC, Kimakjun approved these changes
수고하셨습니다.

2020-11-30 01:23 UTC, merged